### ISSUE TITLE
Issues when installing the gem with gemfile

### ISSUE THREAD

**Issue by hieu9102002** [icalendar/icalendar-recurrence#29]
Hi. I just installed icalendar-recurrence today with gemfile:
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "icalendar-recurrence"
```
with 
```
bundle install
```
and tried to run the example code
```ruby
require 'date' # for parse method
require 'icalendar/recurrence'

ics_string = <<-EOF
BEGIN:VCALENDAR
X-WR-CALNAME:Test Public
X-WR-CALID:f512e378-050c-4366-809a-ef471ce45b09:101165
PRODID:Zimbra-Calendar-Provider
VERSION:2.0
METHOD:PUBLISH
BEGIN:VEVENT
UID:efcb99ae-d540-419c-91fa-42cc2bd9d302
RRULE:FREQ=DAILY;INTERVAL=1
SUMMARY:Every day, except the 28th
DTSTART;VALUE=DATE:20140101
DTEND;VALUE=DATE:20140102
STATUS:CONFIRMED
CLASS:PUBLIC
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
TRANSP:TRANSPARENT
LAST-MODIFIED:20140113T200625Z
DTSTAMP:20140113T200625Z
SEQUENCE:0
EXDATE;VALUE=DATE:20140128
END:VEVENT
END:VCALENDAR
EOF

# An event that occurs every day, starting January 1, 2014 with one excluded 
# date. January 28, 2014 will not appear in the occurrences.
calendars = Icalendar.parse(ics_string)
every_day_except_jan_28 = Array(calendars).first.events.first
puts "Every day except January 28, 2014, occurrences from 2014-01-01 to 2014-02-01:"
puts every_day_except_jan_28.occurrences_between(Date.parse("2014-01-01"), Date.parse("2014-02-01"))
```
and I got the following error: 
```
Traceback (most recent call last):
        2: from c:/Users/MSI GF/Desktop/Swinburne/COS10009/Test/calendar.rb:3:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- icalendar/recurrence (LoadError)
        9: from c:/Users/MSI GF/Desktop/Swinburne/COS10009/Test/calendar.rb:3:in `<main>'
        8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/icalendar-recurrence-1.1.3/lib/icalendar/recurrence.rb:6:in `<top (required)>'
        4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/icalendar-recurrence-1.1.3/lib/icalendar/recurrence/time_util.rb:1:in `<top (required)>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- tzinfo (LoadError)
PS C:\Users\MSI GF\Desktop\Swinburne\COS10009\Test>
```
I tried to create a new ruby bundle going to a different folder and using bundle init, tried importing different files into the code such as icalendar, rubygems, and tried installing icalendar in gemfile but to no avail. What am I doing wrong here?

**Comment by hieu9102002** [comment]
Got it, I had to install tzinfo-data using 
```ruby
gem 'tzinfo-data'
```
then it works
