### ISSUE TITLE
ActiveSupport 7.2 causes specs to fail

### ISSUE THREAD

**Issue by nehresma** [icalendar/icalendar-recurrence#42]
The gemspec specifies ActiveSupport versions `~> 7.1`.

If I clone the repository, then run `bundle install`, it will install the latest ActiveSupport in the 7.x series: version 7.2.2 at the moment.

Then run the specs with `rspec spec` and you'll see there are 2 specs that fail:

```
{main nehresman@weathertop:/tmp/icalendar-recurrence}$ grep activesupport Gemfile.lock 
    activesupport (7.2.2)
  activesupport (~> 7.1)
{main nehresman@weathertop:/tmp/icalendar-recurrence}$ rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 30970
..........F................................F...

Failures:

  1) Event#occurrences_between event repeating weekly with rdates properly includes specified rdates
     Failure/Error: expect(occurrence.end_time).to eq(Time.new 2020, 02, 01, 21, 0, 0, "+00:00")
     
       expected: 2020-02-01 21:00:00.000000000 +0000
            got: 2020-02-01 19:00:00.083333333 +0000
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2020-02-01 21:00:00 +0000
       +2020-02-01 19:00:00 1/12 UTC
       
     # ./spec/lib/recurrence_spec.rb:115:in `block (3 levels) in <top (required)>'

  2) Icalendar::Recurrence::Schedule#occurrences_between returns occurrences within range, including duration spanning #start_time 
     Failure/Error: expect(occurrences.count).to eq(7)
     
       expected: 7
            got: 6
     
       (compared using ==)
     # ./spec/lib/schedule_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.11526 seconds (files took 0.269 seconds to load)
47 examples, 2 failures

Failed examples:

rspec ./spec/lib/recurrence_spec.rb:106 # Event#occurrences_between event repeating weekly with rdates properly includes specified rdates
rspec ./spec/lib/schedule_spec.rb:16 # Icalendar::Recurrence::Schedule#occurrences_between returns occurrences within range, including duration spanning #start_time 

Randomized with seed 30970
```

Now, if I force activesupport 7.1 by changing the gemspec from:
```
  spec.add_development_dependency 'activesupport', '~> 7.1'
```
to
```
  spec.add_development_dependency 'activesupport', '~> 7.1.0'
```

Then reset my environment and bundle install things again, all specs pass:
```
rm Gemfile.lock; rvm gemset delete icalendar-recurrence; rvm gemset create icalendar-recurrence; rvm gemset use icalendar-recurrence; bundle install
...
{main nehresman@weathertop:/tmp/icalendar-recurrence}$ rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 11013
...............................................

Finished in 0.10883 seconds (files took 0.28751 seconds to load)
47 examples, 0 failures

Randomized with seed 11013
```

**Comment by nehresma** [comment]
I'm pretty sure I tracked down the error where the diff was:

```
       Diff:
       @@ -1 +1 @@
       -2020-02-01 21:00:00 +0000
       +2020-02-01 19:00:00 1/12 UTC
```
I believe it stems from ActiveSupport::TimeWithZone actually changing the behavior of the `-` method here:  https://github.com/rails/rails/pull/52031

It no longer calls `.to_time`, and instead calls `getutc`:
https://github.com/rails/rails/pull/52031/files#diff-aa0ae5ccf92f812f874b632afe70375c52772636f927fe6e34ffeaebf54af9d1

Since the `time_object.value` in the `Icalendar::Recurrence::TimeUtil.to_time` method returns a `DateTime`, that `DateTime` never gets converted to a `Time` object as of ActiveSupport 7.2.  This in turn means that the duration calculation is subtracting 2 `DateTime` objects, which returns a `Rational`: `1/12`.

I'm not sure if the fix is as easy as adding an explicit `.to_time` to the `time_object.value` here or not:
https://github.com/icalendar/icalendar-recurrence/blob/main/lib/icalendar/recurrence/time_util.rb#L29

It is the end of the day Friday and I don't have time to investigate further, but I wanted to record what I've found so far.

FWIW, this will likely impact users of Rails 8 as well.
